### PR TITLE
remove ember-cli-template-lint and force latest glimmer/component

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by mehulkar** [comment]
Maybe also change the default test script in package.json to run template lint?

**Comment by NullVoxPopuli** [comment]
imo, linting should be separate from `package.json.scripts.test`. 

there is already a 'lint:hbs' and 'lint:js' to handle lining needs :)

**Comment by mehulkar** [comment]
Yep that works. Didn’t see that in the blueprint before

**Comment by mehulkar** [comment]
The main argument against is that CI systems sometimes assume the test command is “npm test” and if that’s not configurable in that system, by default you won’t get linting in CI.

**Comment by NullVoxPopuli** [comment]
my opinion, but if your CI system doesn't let you adjust stages / add linting steps, it's not a good CI system :-\
however, I think all CI systems allow for this:
 - explicit stages
   - GitLab
   - GitHub Actions
   - Azure DevOps
   - Travis
 - runs a script
   - all of the above
   - Circle CI
   - Bitbucket / Bamboo

For the script scenario, it's super easy to configure:

```bash
#!/bin/bash
#
# e -- exits the script if any command fails
# x -- prints each command before running it
set -ex

yarn lint:js
yarn lint:hbs
yarn test
```

**Comment by mehulkar** [comment]
1. It is a real use case at my company, hard as that might be to believe :). Configuration is possible but usually more trouble than it’s worth.
1. We care about “falling into the pit of success”, so this is more a question of defaults than configuration.
1. Changing the test script for this edge case is trivial, so I’m not too concerned. 

Another side note: the 2019 roadmap RFC mentioned adding a11y rules to the linter by default. If these new lint rules don’t run for first time users, they could be self defeating. See point 2 :)

**Comment by NullVoxPopuli** [comment]
adding things by default is fine -- I'm all for that. :D My main thing is just that linting != testing. :man_shrugging: 
but we've gotten off topic now :)

**Comment by rwjblue** [comment]
FWIW, we (the ember-cli team) had already decided (see [the RFC](https://github.com/emberjs/rfcs/blob/master/text/0121-remove-ember-cli-eslint.md#detailed-design)'s detailed design) to make `npm test` do `lint:js`, `lint:hbs`, and `ember test`. Just haven't implemented yet.

**Pull request merged**
