### PR TITLE
Update for co-location support

### LINKED ISSUE #137: `ember generate component foo-bar` (with no modifiers) generates a template-only component that throws an error on render
Using ember-cli 3.11.0, in an app generated with the ember-octane-blueprint, `ember generate component foo-bar` creates appears to generate a template-only component by default:

image

When trying to render this component (via angle-brackets or curlies), the browser throws this error: 
image

`ember generate component foo-bar --gc` (or `--cc`) creates a .js file as well, alongside the .hbs file:
image

but then ember-cli throws an error:
`(node:9959) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, symlink '/Users/username/posterkiosk-v3/app/components/foo-bar.js' -> '/var/folders/2z/wlt8fkc91ns4_nvrp7nynv_m0000gq/T/broccoli-9959zBmmLpkANVA0/out-176-broccoli_persistent_filter_template_compiler/posterkiosk-v3/components/foo-bar.js'`

/edit: I just realized, in case it matters, I created the new project via `npx ember-cli new appname -b @ember/octane-app-blueprint` earlier this afternoon, and don't have ember-cli installed globally, so I'm using `yarn ember generate component`.

### PR DESCRIPTION
**Pull request by chancancode**
I'm not sure if this is a good idea, but this will fix #137

### CODE REVIEW

**Comment by chancancode** [comment]
@NullVoxPopuli I think there are some TODOs in the code, and also we didn't do any caching. It'll probably be a problem for existing apps being migrated to Octane, but for creating new apps to play with, it's hardly noticeable.

**Comment by rwjblue** [comment]
Seems fine to me.

**Comment by jenweber** [comment]
This change resulted in a breaking error, `template$$1.asWrappedLayout` for freshly generated apps. Can we revert?

**Comment by chancancode** [comment]
Fixed in https://github.com/ember-cli/ember-cli-htmlbars/commit/a640658a151fe472fb4a3ecc65a8a11ebf2848f1

**Pull request merged**
