### PR TITLE
Upgrade blueprint to ember-cli 3.6

### PR DESCRIPTION
**Pull request by Gaurav0**
done via ember-cli-update

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
we don't have tests atm. do the sample components still work?

**Comment by Gaurav0** [comment]
@rwjblue the files/* already matched those from ember-cli 3.6.

**Comment by Gaurav0** [comment]
@NullVoxPopuli I verified by publishing to @gaurav9576/ember-octane-blueprint and then generating an app, then running ember s.

**Comment by NullVoxPopuli** [comment]
LGTM

**Pull request merged**
